exercises = [
    {
        "id": 1,
        "name": "Bicycle Crunch",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 2,
        "name": "Cable Crunch",
        "muscle": "Core",
        "equipment": ["Cable Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 3,
        "name": "Cable Twist",
        "muscle": "Core",
        "equipment": ["Cable Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 4,
        "name": "Crunch",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 5,
        "name": "Cross Body Crunch",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 6,
        "name": "Crunch (Machine)",
        "muscle": "Core",
        "equipment": ["Crunch Machine"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 7,
        "name": "Flat Knee Raise",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 8,
        "name": "Flat Leg Raise",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 9,
        "name": "Hanging Knee Raise",
        "muscle": "Core",
        "equipment": ["Bar"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 10,
        "name": "Hanging Leg Raise",
        "muscle": "Core",
        "equipment": ["Bar"],
        "difficulty": "Advanced",
        "type": "Strength",
    },
    {
        "id": 11,
        "name": "Plank",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Beginner",
        "type": "Isometric",
    },
    {
        "id": 12,
        "name": "Oblique Crunch",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 13,
        "name": "Russian Twist",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 14,
        "name": "Side Plank",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Intermediate",
        "type": "Isometric",
    },
    {
        "id": 15,
        "name": "Sit-up",
        "muscle": "Core",
        "equipment": ["Bodyweight"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 16,
        "name": "Bench Dip",
        "muscle": "Triceps",
        "equipment": ["Bench"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 17,
        "name": "Tricep Dip",
        "muscle": "Triceps",
        "equipment": ["Dip Bars"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 18,
        "name": "Cable Tricep Pushdown",
        "muscle": "Triceps",
        "equipment": ["Cable Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 19,
        "name": "Tricep Extension",
        "muscle": "Triceps",
        "equipment": ["Dumbbell", "Barbell", "Cable Machine", "Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 20,
        "name": "Overhead Tricep Extension",
        "muscle": "Triceps",
        "equipment": ["Dumbbell", "Barbell", "Cable Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 21,
        "name": "Skull Crusher",
        "muscle": "Triceps",
        "equipment": ["Dumbbell", "Barbell"],
        "difficulty": "Advanced",
        "type": "Strength",
    },
    {
        "id": 22,
        "name": "Tricep Kickback",
        "muscle": "Triceps",
        "equipment": ["Dumbbell", "Cable Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 23,
        "name": "Bicep Curl",
        "muscle": "Biceps",
        "equipment": ["Dumbbell", "Barbell", "Cable Machine"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 24,
        "name": "Hammer Curl",
        "muscle": "Biceps",
        "equipment": ["Dumbbell", "Cable Machine"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 25,
        "name": "Incline Curl",
        "muscle": "Biceps",
        "equipment": ["Dumbbell"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 26,
        "name": "Preacher Curl",
        "muscle": "Biceps",
        "equipment": ["Dumbbell", "Barbell", "Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 27,
        "name": "Reverse Curl",
        "muscle": "Forearms",
        "equipment": ["Dumbbell", "Barbell"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 28,
        "name": "Shoulder Press",
        "muscle": "Shoulders",
        "equipment": ["Dumbbell", "Machine", "Barbell"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 29,
        "name": "Push-up",
        "muscle": "Chest",
        "equipment": ["Bodyweight"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 30,
        "name": "Pull-up",
        "muscle": "Back",
        "equipment": ["Bar"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 31,
        "name": "Squat",
        "muscle": "Legs",
        "equipment": ["Bodyweight", "Barbell"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 32,
        "name": "Bench Press",
        "muscle": "Chest",
        "equipment": ["Barbell", "Dumbbell"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 33,
        "name": "Deadlift",
        "muscle": "Back",
        "equipment": ["Barbell", "Dumbbell"],
        "difficulty": "Advanced",
        "type": "Strength",
    },
    {
        "id": 34,
        "name": "Lunges",
        "muscle": "Legs",
        "equipment": ["Bodyweight", "Dumbbell", "Barbell"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 35,
        "name": "Leg Press",
        "muscle": "Legs",
        "equipment": ["Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 36,
        "name": "Lat Pulldown",
        "muscle": "Back",
        "equipment": ["Machine"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 37,
        "name": "Chest Fly",
        "muscle": "Chest",
        "equipment": ["Dumbbell", "Machine"],
        "difficulty": "Intermediate",
        "type": "Strength",
    },
    {
        "id": 38,
        "name": "Calf Raise",
        "muscle": "Legs",
        "equipment": ["Bodyweight", "Dumbbell", "Barbell", "Machine"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
    {
        "id": 39,
        "name": "Back Extension",
        "muscle": "Back",
        "equipment": ["Bodyweight", "Dumbbell"],
        "difficulty": "Beginner",
        "type": "Strength",
    },
]
